apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx-deployment-service"
  namespace: "application"
  labels:
    app: "nginx"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "nginx"
  type: "LoadBalancer"
  loadBalancerIP: ""